name: pipeline release

on:
  release:
    types:
      - created
jobs:
  push_to_registry:
    name: run tests and metrics + push docker image and pip package
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: install dependencies python3
        run: |
          python3 -m pip install --upgrade pip
          pip install mutatest coverage pylint termcolor pep517 freezegun
      - name: pylint
        run: |
          pylint pypodo/__pypodo__.py    
      - name: pytest
        run: |
          python3 -m unittest -v pypodo/__pypodo__test.py        
      - name: mutatest
        run: |
          mutatest            
      - name: coverage
        run: |
          coverage run && coverage report                 
      - name: install docker
        uses: docker-practice/actions-setup-docker@master
      - name : run test
        run: ./pypodo_github.sh
      - name: push on docker hub latest
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: thibaultgarcon/pypodo
          tags: latest   
      - name: build pip
        run: python3 -m pep517.build --source --binary --out-dir dist/ .
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}          
  