name: pipeline release

on:
  release:
    types:
      - created
jobs:
  push_to_registry:
    name: run tests + push pip package
    runs-on: ubuntu-22.04
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: install python3
        uses: actions/setup-python@v2
        #with:
        #  python-version: '3.11'
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      #installation          
      - name: install pypodo
        run: |
          pip install .
      #test
      - name: Launch test
        uses: ./.github/actions/test 
      - name: install pep517
        run: |
          pip install pep517        
      - name: build pip
        run: python3 -m pep517.build --source --binary --out-dir dist/ .
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
      - name: Deduce relase
        id: vars
        run: echo ::set-output name=relase_tag::$(grep version setup.py | cut -d "\"" -f2)
      - name: tweet
        env: 
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          VERSION: ${{ steps.vars.outputs.relase_tag }}
        run: pip install twython && python .github/publish_tweet.py             
