name: test ubuntulatest pythonlatest

on:
  workflow_dispatch:

jobs:
  full_test:       
    runs-on: 'ubuntu-20.04'
    name: test package with ubuntu20.04 et python3.9
    steps:
      #preparation
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64                            
      - name: update pip
        run: |
          python -m pip install --upgrade pip
      #installation          
      - name: install pypodo
        run: |
          pip install .
      #test
      - name: Launch test
        uses: ./.github/actions/test 
    
